[build]
  # Build command for the frontend
  command = "cd ci-cd-dashboard && npm run build"
  
  # Directory to publish
  publish = "ci-cd-dashboard/build"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirect API calls to the backend (if deployed separately)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.render.com/api/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
