services:
  - type: web
    name: monitoring-dashboard-backend
    runtime: node
    region: ohio
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: GITHUB_TOKEN
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
